# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
#Uncomment this line if you're using Swift
use_frameworks!

target 'twatter' do
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'
  pod 'ChameleonFramework/Swift'
  pod 'ActiveLabel'
end

